/*
 *
 * hymk/sysinfo.h
 *
 * (C)2004 by Friedrich Gräter
 *
 * This file is distributed under the terms of
 * the GNU Lesser General Public License, Version 2. You
 * should have received a copy of this license (e.g. in 
 * the file 'copying.library'). 
 *
 * Info page content IDs
 *
 */
#ifndef _SYSINFO_H
#define _SYSINFO_H

/*
 * The main info page entries
 *
 */
#define MAININFO_CURRENT_PROCESS	0
#define MAININFO_CURRENT_THREAD		1
#define MAININFO_PROC_TABLE_ENTRY	2
#define MAININFO_THRD_TABLE_ENTRY	3
#define MAININFO_KERNEL_MAJOR		4
#define MAININFO_KERNEL_MINOR		5
#define MAININFO_KERNEL_REVISION	6
#define MAININFO_RTC_COUNTER_LOW	7
#define MAININFO_RTC_COUNTER_HIGH	8
#define MAININFO_CPU_ID_CODE		9
#define MAININFO_PAGE_SIZE		10
#define MAININFO_MAX_PAGE_OPERATION	11

#define MAININFO_X86_CPU_NAME_PART_1	100
#define MAININFO_X86_CPU_NAME_PART_2	101
#define MAININFO_X86_CPU_NAME_PART_3	102
#define MAININFO_X86_CPU_TYPE		103
#define MAININFO_X86_CPU_FAMILY		104
#define MAININFO_X86_CPU_MODEL		105
#define MAININFO_X86_CPU_STEPPING	106
#define MAININFO_X86_RAM_SIZE		107

/*
 * The process table entries
 *
 */
#define PRCTAB_IS_USED			0
#define PRCTAB_IS_DEFUNCT		1
#define PRCTAB_SID			2
#define PRCTAB_CONTROLLER_THREAD_SID	3
#define PRCTAB_CONTROLLER_THREAD_DESCR	4
#define PRCTAB_PAGE_COUNT		5
#define PRCTAB_IO_ACCESS_RIGHTS		6
#define PRCTAB_PAGEDIR_PHYSICAL_ADDR	7
#define PRCTAB_IS_ROOT			8
#define PRCTAB_IS_PAGED			9
#define PRCTAB_THREAD_COUNT		10
#define PRCTAB_THREAD_LIST_BEGIN	11
#define PRCTAB_UNIQUE_ID		12

#define PRCTAB_X86_MMTABLE		1024

/*
 * The thread table entries
 *
 */
#define THRTAB_IS_USED			0
#define THRTAB_SID			1
#define THRTAB_PROCESS_SID		2
#define THRTAB_SYNC_SID			3
#define THRTAB_MEMORY_OP_SID		4
#define THRTAB_MEMORY_OP_DESTADR	5
#define THRTAB_MEMORY_OP_MAXSIZE	6
#define THRTAB_MEMORY_OP_ALLOWED	7
#define THRTAB_KERNEL_STACK_ADDRESS	8
#define THRTAB_PROCESS_DESCR		9
#define THRTAB_THRSTAT_FLAGS		10
#define THRTAB_IRQ_RECV_NUMBER		11
#define THRTAB_FREEZE_COUNTER		12
#define THRTAB_RUNQUEUE_PREV		13
#define THRTAB_RUNQUEUE_NEXT		14
/* THRTAB_SOFTINT_LISTENER_SID is used in sysc.s ! */
#define THRTAB_SOFTINT_LISTENER_SID	15
#define THRTAB_EFFECTIVE_PRIORITY	16
#define THRTAB_STATIC_PRIORITY		17
#define THRTAB_SCHEDULING_CLASS		18
#define THRTAB_TIMEOUT_LOW		19
#define THRTAB_TIMEOUT_HIGH		20

#define THRTAB_LAST_EXCPT_NUMBER	21
#define THRTAB_LAST_EXCPT_NR_PLATTFORM	22
#define THRTAB_LAST_EXCPT_ADDRESS	23
#define THRTAB_LAST_EXCPT_ERROR_CODE	24
#define THRTAB_PAGEFAULT_DESCRIPTOR	25
#define THRTAB_PAGEFAULT_LINEAR_ADDRESS	26

#define THRTAB_PREV_THREAD_OF_PROC	27
#define THRTAB_NEXT_THREAD_OF_PROC	28

#define THRTAB_RECEIVED_SOFTINT		29
#define THRTAB_RECV_LISTEN_TO		30

#define THRTAB_UNIQUE_ID		31

/* x86-Implementation defined elements */
#define THRTAB_CUR_SYNC_QUEUE_PREV	50
#define THRTAB_CUR_SYNC_QUEUE_NEXT	51
#define THRTAB_OWN_SYNC_QUEUE_BEGIN	52
#define THRTAB_TIMEOUT_QUEUE_PREV	53
#define THRTAB_TIMEOUT_QUEUE_NEXT	54

/* Kernel stack pointer */
#define THRTAB_X86_KERNEL_POINTER	100
/* Physical address of the thread local storage */
#define THRTAB_X86_TLS_PHYS_ADDRESS	101	
/* x87 FPU Stack */
#define THRTAB_X86_FPU_STACK		768

#define THRTAB_LOCAL_STORAGE_BEGIN	1024

/* Thread status flags (acc. THRTAB_THRSTAT_FLAGS) */
#define THRSTAT_BUSY			1
#define THRSTAT_KERNEL_MODE		2 
#define THRSTAT_IRQ			4 
#define THRSTAT_IRQ_HANDLING 		8 
#define THRSTAT_SYNC	 		16
#define THRSTAT_TIMEOUT			32 
#define THRSTAT_RECV_SOFTINT		64 
#define THRSTAT_FREEZED			128
#define THRSTAT_WAIT_HYPAGED		256
#define THRSTAT_PROC_DEFUNC		512
#define THRSTAT_TRACE_ONLY		1024

#define THRSTAT_OTHER_FREEZE		(THRSTAT_IRQ|THRSTAT_SYNC|THRSTAT_RECV_SOFTINT|THRSTAT_WAIT_HYPAGED|THRSTAT_PROC_DEFUNC)

/* Priority constants */
#define THRPRIOR_MIN		0
#define THRPRIOR_MAX		40

#define THRPRIOR_VERY_HIGH	40
#define THRPRIOR_HIGH		30
#define THRPRIOR_NORMAL		20
#define THRPRIOR_LOW		10
#define THRPRIOR_LAZY		0

/* Scheduling class constants */
#define THRSCHED_CLASS_MIN	0
#define THRSCHED_CLASS_MAX	0

#define THRSCHED_CLASS_NORMAL	0 

#endif
